* Added a routine to import AWS access keys from a file, to shell variables * Put Dropbox mounts back to what they were before

diff --git a/.bash/variables b/.bash/variables
--- a/.bash/variables
+++ b/.bash/variables
@@ -5,15 +5,9 @@ export EDITOR=vim
 
 [ -d "$HOME/Library/Android/sdk" ] && export ANDROID_HOME="$HOME/Library/Android/sdk"
 
-if [ -d "$HOME/Dropbox (Zillow Group)" ]; then
-	export DROPBOX="$HOME/Dropbox (Zillow Group)"
-	if [ -d "$DROPBOX/Workspace" ]; then
-		export WORKSPACE="$DROPBOX/Workspace"
-		if [ -d "$WORKSPACE/repos" ]; then
-			export REPOS="$WORKSPACE/repos"
-		fi
-	fi
-fi
+[ -d "$HOME/Dropbox (Zillow Group)" ] && export DROPBOX="$HOME/Dropbox (Zillow Group)"
+[ -d "$HOME/Workspace" ] && export WORKSPACE="$HOME/Workspace"
+[ -d "$WORKSPACE/repos" ] && export REPOS="$WORKSPACE/repos"
 
 if [ -d "/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home" ]; then
 	export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home"
@@ -21,8 +15,8 @@ else
 	>&2 echo "JAVA_HOME of \"/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home\" does not exist. Atlassian SDK commands will not work." 
 fi
 
-if [ -d "$DROPBOX/Workspace/repos" ]; then
-    export REPOS="$DROPBOX/Workspace/repos"
+if [ -d "$HOME/Workspace/repos" ]; then
+    export REPOS="$HOME/Workspace/repos"
     export GUARD_DIR="$REPOS"
 fi
 LS_CMD_set () {
@@ -42,3 +36,15 @@ LS_CMD_set
 # Useful for creating the remote on new systems.
 export DOTFILES_REMOTE="https://github.com/phasetwenty/dotfiles.git"
 
+READ_AWS_KEYS () {
+	if ! which -s jq; then
+		>&2 echo "jq missing, cannot import AWS keys."
+		return
+	elif [ ! -f "$HOME/.aws_access_keys" ]; then
+		>&2 echo "~/.aws_access_keys missing, cannot import AWS keys."
+	fi
+
+	AWS_PUBLIC_KEY=$(jq -rM .public "$HOME/.aws_access_keys")
+    AWS_PRIVATE_KEY=$(jq -rM .private "$HOME/.aws_access_keys")
+}
+READ_AWS_KEYS
